# Docker Login: https://github.com/marketplace/actions/docker-login
# Build and push Docker images: https://github.com/marketplace/actions/build-and-push-docker-images

name: Publish image

on:
  workflow_call:
    inputs:
      TAG:
        type: string
        required: true
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  push_to_registry:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ inputs.TAG != '' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build & Publish Docker image
        id: build_image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "komelt/grafana:${{ inputs.TAG }}"
          build-args: |
            "GRAFANA_VERSION=${{ inputs.TAG }}"
          no-cache: false
          load: true
      - name: Echo Built Image Digest
        run: echo "The image digest is ${{ steps.build_image.outputs.metadata }}"