name: Scheduled Docker image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

jobs:
  test_docker_image:
    uses: ./.github/workflows/test-docker-image.yml

  publish_docker_image:
    needs: test_docker_image
    uses: ./.github/workflows/publish-docker-image.yml