name: Scheduled Docker image

on:
  push:
    branches:
      - "*"
  schedule:
    - cron: '0 12 * * *'

jobs:
  get-all-images:
    runs-on: ubuntu-latest
    steps:
      - name: "Test Docker command"
        run: docker ps