name: Scheduled Docker image

on:
  push:
    branches:
      - "*"
  schedule:
    - cron: '0 12 * * *'

jobs:
  process_image_tags:
    name: Process Grafana tags
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - name: Fetch image tags
        id: fetch_tags
        run: |
          echo "Fetching tags..."
          TAGS=$(curl -s "https://registry.hub.docker.com/v2/repositories/grafana/grafana/tags" | jq -r ".results[].name" | paste -sd "," -)
          echo $TAGS
          echo "tags=$TAGS" >> $GITHUB_OUTPUT 

      - name: Create JSON matrix
        id: set_matrix
        env:
          TAGS: ${{ steps.fetch_tags.outputs.TAGS }}
        run: |
          # Convert comma-separated tags into a JSON array
          JSON_ARRAY=$(echo $TAGS | jq -R -s -c 'split(",")[:-1]')
          echo "matrix={\"include\":$(echo $JSON_ARRAY | jq -c '[.[] | {"tag": .}]')}" >> $GITHUB_OUTPUT

  test_tag:
    name: Test (${{ matrix.tag }})
    needs: process_image_tags
    strategy:
      matrix: ${{fromJson(needs.process_image_tags.outputs.matrix)}}
    with:
      TAG: ${{ matrix.tag }}
    uses: ./.github/workflows/test.yml

  push_tag:
    name: Push
    needs: test_tag
    runs-on: ubuntu-latest
    steps:
      - name: Log test output
        run: echo "${{ needs.test_tag.outputs.successful-tags }}"
        