name: Scheduler

on:
  push:
    branches:
      - '*'
  schedule:
    - cron: '0 12 * * *'

jobs:
  get_tags:
    name: Get Image Tags
    uses: ./.github/workflows/get_tags.yml

  test_tags:
    name: Test (${{ matrix.tag }})
    needs: get_tags
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get_tags.outputs.TAGS_JSON_MATRIX) }}
    with:
      TAG: ${{ matrix.tag }}
    uses: ./.github/workflows/test.yml

  agregate_updated_tags:
    name: Agregate Tags
    needs: test_tags
    if: always()
    uses: ./.github/workflows/agregate_updated_tags.yml
    

  publish_tags:
    name: Publish (${{ matrix.tag }})
    needs: agregate_updated_tags
    if: ${{ always() && github.repository == 'main' }}
    secrets: inherit
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.agregate_updated_tags.outputs.UPDATED_TAGS_MATRIX) }}
    with:
      TAG: ${{ matrix.tag }}
    uses: ./.github/workflows/publish.yml