name: Scheduled Docker image

on:
  push:
    branches:
      - "*"
  schedule:
    - cron: '0 12 * * *'

jobs:
  process-tags:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Fetch tags
        id: fetch-tags
        run: |
          echo "Fetching tags..."
          TAGS=$(curl -s "https://registry.hub.docker.com/v2/repositories/grafana/grafana/tags" | jq -r ".results[].name" | paste -sd "," -)
          echo $TAGS
          echo "tags=$TAGS" >> $GITHUB_OUTPUT 

      - name: Create JSON matrix
        id: set-matrix
        env:
          TAGS: ${{ steps.fetch-tags.outputs.TAGS }}
        run: |
          # Convert comma-separated tags into a JSON array
          JSON_ARRAY=$(echo $TAGS | jq -R -s -c 'split(",")[:-1]')
          echo "matrix={\"include\":$(echo $JSON_ARRAY | jq -c '[.[] | {"tag": .}]')}" >> $GITHUB_OUTPUT

  build:
    needs: process-tags
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.process-tags.outputs.matrix)}}
    steps:
    - name: Process Tag
      run: |
        echo "Processing tag ${{ matrix.tag }}"
        # Replace the echo command with your processing steps
        