# Build and push Docker images: https://github.com/marketplace/actions/build-and-push-docker-images

name: Scheduled build Docker image

on:
  workflow_call:

jobs:
  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          no-cache: true
    