# Build and push Docker images: https://github.com/marketplace/actions/build-and-push-docker-images

name: Test image

on:
  workflow_call:
    inputs:
      TAG:
        type: string
        required: true
    outputs:
      successful-tag:
        description: "Sucessfully passed tag"
        value: ${{ jobs.build_test.outputs.successful-tag }}

jobs:
  build_test:
    name: Build Test
    runs-on: ubuntu-latest
    outputs:
      successful-tag: ${{ steps.tag_output.outputs.tag }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build 'komelt/grafana:${{ inputs.TAG }}'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: "komelt/grafana:${{ inputs.TAG }}"
          no-cache: true

      - name: Output as sucessfull
        id: tag_output
        if: ${{ success() }}
        run: echo "successful-tag=${{ inputs.TAG }}" >> $GITHUB_OUTPUT
    