# Build and push Docker images: https://github.com/marketplace/actions/build-and-push-docker-images

name: Test Docker image

on:
  workflow_call:
    inputs:
      TAG:
        type: string
        required: true

jobs:
  test_image_tag:
    name: Test Docker Image
    runs-on: ubuntu-latest
    steps:

      - name: Log tag
        run: echo ${{ inputs.TAG }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: "komelt/grafana:${{ inputs.TAG }}"
          no-cache: true
    